name: Check and test

on: [push, pull_request, workflow_dispatch]

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_USERNAME: ${{ secrets.ARTIFACTS_USERNAME }}
      ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      ARTIFACTS_CHARACTER: ${{ secrets.ARTIFACTS_CHARACTER }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install --frozen-lockfile
      - name: "commitlint: Validate current commit (last commit)"
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose
      - name: "commitlint: Validate PR commits"
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: bun run check
      - run: bun test
